# Generated by Django 4.1.5 on 2023-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RelationList",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "relation_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScholarList",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField(blank=True, db_column="Year", null=True)),
                (
                    "title",
                    models.CharField(db_column="Title", max_length=255, unique=True),
                ),
                ("author", models.CharField(db_column="Author", max_length=255)),
            ],
            options={
                "db_table": "scholar_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SnslabList",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
            ],
            options={
                "db_table": "snslab_list",
                "managed": False,
            },
        ),
    ]
